# Generated by Django 6.0.3 on 2026-03-13 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='gmodel',
        ),
    ]
